CREATE TABLE SOCCER(
   USERNO NUMBER PRIMARY KEY
 , USERNAME VARCHAR2(15) NOT NULL
 , USERPOSITION VARCHAR2(15) NOT NULL
 , SALARY NUMBER
 , USERTEAM VARCHAR2(20)
 , ENROLLDATE DATE DEFAULT SYSDATE NOT NULL
   );
INSERT
  INTO 
  	   SOCCER  
  VALUES(7,'RONALDO','FW',50000000,'포르투갈',SYSDATE);

INSERT 
  INTO
       SOCCER
 VALUES(10,'MESSI','LF',600000000,'아르헨티나',SYSDATE);

COMMIT;

SELECT
       *
  FROM 
       SOCCER;
SELECT 
		*
  FROM
       SOCCER;
   
        
  
 
